version: '3.9'

services:
    react:
      build:
        args:
          - NODE_VER=22.5.1-slim
        context: .
        dockerfile: Dockerfile
      tty: true
      volumes:
        - ./frontend:/app
        - node_modules:/app/node_modules
      ports:
        - '5173:5173'

volumes:
  node_modules:
